# ansible/roles/zabbix/tasks/install.yml
- name: Install dependencies
  apt:
    name:
      - apache2
      - php
      - php-pgsql
      - php-xml
      - php-bcmath
      - php-mbstring
    state: present
    update_cache: yes

- name: Download Zabbix package
  command: wget -O /tmp/zabbix-release.deb https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb

- name: Install Zabbix release package
  apt:
    deb: /tmp/zabbix-release.deb
    state: present
    update_cache: yes

- name: Install Zabbix server and agent for PostgreSQL
  apt:
    name:
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-agent
    state: present

- name: Ensure Zabbix configuration directory exists
  file:
    path: /etc/zabbix
    state: directory
    mode: '0755'

- name: Configure Zabbix server
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify:
    - Restart Zabbix server

- name: Configure PHP for Zabbix frontend
  lineinfile:
    path: /etc/zabbix/apache.conf
    regexp: "^php_value date.timezone"
    line: "php_value date.timezone Europe/Moscow"  # Adjust timezone as needed

- name: Start and enable Zabbix and Apache services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - zabbix-server
    - zabbix-agent
    - apache2