---

- name: Install Java (required for Keycloak)
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Install unzip (required for Keycloak installation)
  apt:
    name: unzip
    state: present
    update_cache: yes

- name: Ensure Keycloak directory exists
  file:
    path: /opt/keycloak/conf
    state: directory
    mode: '0755'

- name: Create Keycloak directory
  file:
    path: /opt/keycloak
    state: directory
    mode: '0755'

- name: Download Keycloak
  get_url:
    url: "https://github.com/keycloak/keycloak/releases/download/15.0.2/keycloak-15.0.2.zip"
    dest: /opt/keycloak/keycloak.zip
    mode: '0644'

- name: Unzip Keycloak
  unarchive:
    src: /opt/keycloak/keycloak.zip
    dest: /opt/keycloak/
    remote_src: yes
    creates: /opt/keycloak/keycloak-15.0.2

- name: Create a symbolic link to Keycloak folder
  file:
    src: /opt/keycloak/keycloak-15.0.2
    dest: /opt/keycloak/current
    state: link

- name: Configure Keycloak to use PostgreSQL
  template:
      src: keycloak-db-config.j2
      dest: /opt/keycloak/conf/keycloak.conf
  notify:
        - Restart Keycloak