- name: Configure Keycloak, Samba, Zabbix
  hosts: all
  become: true
  roles:
    - role: samba
      when: inventory_hostname in groups['samba']

    - role: keycloak
      when: inventory_hostname in groups['keycloak']

    - role: zabbix
      when: inventory_hostname in groups['zabbix']