- name: Configure Keycloak, Samba, Zabbix, and PostgreSQL
  hosts: all
  become: true
  roles:
    #- role: postgres
    #  when: inventory_hostname in groups['postgres']

    - role: keycloak
      when: inventory_hostname in groups['keycloak']

    - role: samba
      when: inventory_hostname in groups['samba']

    - role: zabbix
      when: inventory_hostname in groups['zabbix']